### ISSUE TITLE
latest release does not work

### ISSUE THREAD

**Issue by santillaner** [sebbo2002/ical-generator#106]
When I ```require("ical-generator")``` on node 6 node 8 and node 10, I get 
````
Error: Cannot find module 'ical-generator'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
````

Both on Mac OS X and on Ubuntu. This happened since yesterday's release. Before that, it worked fine.

**Comment by brianhv** [comment]
Is it possible this mistake crept back into 1.2.0? I'm getting a `Cannot find module` error with 1.2.0 but not with 1.1.1.

**Comment by sebbo2002** [comment]
@brianhv A pretty same one, I'm sorry. Published 1.2.1 a few seconds ago…

**Comment by brianhv** [comment]
1.2.1 works. Thanks for the quick fix!
