### ISSUE TITLE
Process should not be killed when data are not valid

### ISSUE THREAD

**Issue by ernho** [sebbo2002/ical-generator#144]
this is not good that the process is killed

Error: Unhandled "error" event. (`organizer` isn't formated correctly. See https://github.com/sebbo2002/ical-generator#organizerstringobject-organizer)
   at Function.emit (events.js:186:19)
   at Immediate._onImmediate (/node-shared/node_modules/mongoose/lib/query.js:3128:23)
   at runCallback (timers.js:810:20)
   at tryOnImmediate (timers.js:768:5)
   at processImmediate [as _immediateCallback] (timers.js:745:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by sebbo2002** [comment]
Please use [`try`/`catch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) to handle these errors as the process is killed by node itself. This library only throws an error.

Please reopen this issue in case you have additional questions regarding this topic.
