### ISSUE TITLE
SyntaxError [unexpected identifier]: Import ical from ical-generator

### ISSUE THREAD

**Issue by borrougagnou** [sebbo2002/ical-generator#250]
Hello, I try to use your "ical-generator"
but I'm blocked...

- I import `ical-generator` / `ical-generator@next` with npm (v2.0.0 / v2.1.0-develop.2)
- I import `http` and `dayjs` with npm
- I create app.js and paste the code into this.
```bash
&> node app.js
import ical from 'ical-generator';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

I do same thing with typescript,
- create index.ts
- paste the code
- launch like this:
```bash
$> tsc --init
message TS6071: Successfully created a tsconfig.json file.
$> tsc index.ts
index.ts:2:18 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

2 import http from 'http';
                   ~~~~~~

index.ts:6:12 - error TS2304: Cannot find name 'moment'.

6     start: moment(),
             ~~~~~~

index.ts:7:10 - error TS2304: Cannot find name 'moment'.

7     end: moment().add(1, 'hour'),
           ~~~~~~

node_modules/ical-generator/dist/calendar.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.

1 /// <reference types="node" />
                        ~~~~

node_modules/ical-generator/dist/calendar.d.ts:2:31 - error TS2307: Cannot find module 'moment-timezone' or its corresponding type declarations.

2 import type { Duration } from 'moment-timezone';
                                ~~~~~~~~~~~~~~~~~

node_modules/ical-generator/dist/calendar.d.ts:4:32 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

4 import { ServerResponse } from 'http';
                                 ~~~~~~

node_modules/ical-generator/dist/calendar.d.ts:347:35 - error TS2503: Cannot find namespace 'NodeJS'.

347     save(path: string, cb?: (err: NodeJS.ErrnoException | null) => void): this;
                                      ~~~~~~

node_modules/ical-generator/dist/event.d.ts:1:28 - error TS2307: Cannot find module 'rrule' or its corresponding type declarations.

1 import type { RRule } from 'rrule';
                             ~~~~~~~

node_modules/ical-generator/dist/tools.d.ts:1:39 - error TS2307: Cannot find module 'moment' or its corresponding type declarations.

1 import type { Moment, Duration } from 'moment';
                                        ~~~~~~~~

node_modules/ical-generator/dist/tools.d.ts:2:41 - error TS2307: Cannot find module 'moment-timezone' or its corresponding type declarations.

2 import type { Moment as MomentTZ } from 'moment-timezone';
                                          ~~~~~~~~~~~~~~~~~

node_modules/ical-generator/dist/tools.d.ts:4:48 - error TS2307: Cannot find module 'luxon' or its corresponding type declarations.

4 import type { DateTime as LuxonDateTime } from 'luxon';
                                                 ~~~~~~~

node_modules/ical-generator/dist/tools.d.ts:5:28 - error TS2307: Cannot find module 'rrule' or its corresponding type declarations.

5 import type { RRule } from 'rrule';
                             ~~~~~~~

node_modules/ical-generator/dist/types.d.ts:1:29 - error TS2307: Cannot find module 'moment' or its corresponding type declarations.

1 import type { Moment } from 'moment';
                              ~~~~~~~~

node_modules/ical-generator/dist/types.d.ts:2:41 - error TS2307: Cannot find module 'moment-timezone' or its corresponding type declarations.

2 import type { Moment as MomentTZ } from 'moment-timezone';
                                          ~~~~~~~~~~~~~~~~~

node_modules/ical-generator/dist/types.d.ts:4:48 - error TS2307: Cannot find module 'luxon' or its corresponding type declarations.

4 import type { DateTime as LuxonDateTime } from 'luxon';
                                                 ~~~~~~~


Found 15 errors.

```

I would like to know if I did something wrong ?

Regards.

**Comment by sebbo2002** [comment]
@borrougagnou Okay, so if you are using JavaScript and not using the ES6 import syntax, you can also use good old require like `const ical = require('ical-generator').default;`

If you want to use Typescript, you have to install some dependencies like `moment` or `luxon`, otherwise Typescript does not know these objects. Please make sure that you use npm > 6, then the peerDependencies will be [installed automatically](https://github.com/sebbo2002/ical-generator#i-use-typescript-and-get-ts2307-cannot-find-module-errors).
